import { Email } from '@/domain/value-objects/Email';
import { UserRole, UserSpecialty } from '@/domain/enums/';

// Types
interface UserPropsDomain {
  id: string;
  email: Email;
  name: string;
  lastName: string;
  role: UserRole;
  phone: string;
  specialty: UserSpecialty;
  avatar: string | null;
  passwordHash: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Entity
export class User {
  // Identity
  private id: string;

  // Data
  private email: Email;
  private name: string;
  private lastName: string;
  private role: UserRole;
  private phone: string;
  private specialty: UserSpecialty;
  private passwordHash: string;
  private isActive: boolean;
  private avatar: string | null;

  // Audit
  private readonly createdAt: Date;
  private updatedAt: Date;

  // Constructor
  private constructor(props: UserPropsDomain) {
    this.id = props.id;
    this.email = props.email;
    this.name = props.name;
    this.lastName = props.lastName;
    this.role = props.role;
    this.phone = props.phone;
    this.specialty = props.specialty;
    this.passwordHash = props.passwordHash;
    this.isActive = props.isActive;
    this.createdAt = props.createdAt;
    this.avatar = props.avatar;
    this.updatedAt = props.updatedAt;
  }

  // Factory for NEW users
  //? The id will be generated by MongoDB as _id which is an ObjectId upon insertion
  static create(props: {
    email: Email;
    name: string;
    lastName: string;
    passwordHash: string;
    role: UserRole;
    phone: string;
    specialty: UserSpecialty;
    avatar?: string | null;
  }): User {
    if (!props.name || props.name.trim().length === 0) {
      throw new Error('Invalid name');
    }

    if (!props.lastName || props.lastName.trim().length === 0) {
      throw new Error('Invalid last name');
    }

    if (!props.passwordHash || props.passwordHash.trim().length === 0) {
      throw new Error('Invalid password');
    }

    if (!Object.values(UserRole).includes(props.role)) {
      throw new Error('Invalid role');
    }

    if (!Object.values(UserSpecialty).includes(props.specialty)) {
      throw new Error('Invalid specialty');
    }

    const now = new Date();

    return new User({
      id: '', //? Temporary placeholder, real id comes from MongoDB as _id which is an ObjectId upon insertion
      email: props.email,
      name: props.name.trim(),
      lastName: props.lastName.trim(),
      passwordHash: props.passwordHash,
      role: props.role,
      phone: props.phone,
      specialty: props.specialty,
      avatar: props.avatar ?? null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });
  }

  // fromPersistence: Means how to rehydrate the entity from data stored in the database
  static fromPersistence(props: UserPropsDomain): User {
    if (!props.id || props.id.trim().length === 0) {
      throw new Error('Invalid id');
    }

    return new User(props);
  }

  // Behavior
  changePasswordHash(passwordHash: string): void {
    if (!passwordHash || passwordHash.trim().length === 0) {
      throw new Error('Invalid password');
    }

    this.passwordHash = passwordHash;
    this.updatedAt = new Date();
  }

  changeEmail(newEmail: Email): void {
    this.email = newEmail;
    this.updatedAt = new Date();
  }

  deactivate(): void {
    this.isActive = false;
    this.updatedAt = new Date();
  }

  changeSpecialty(specialty: UserSpecialty): void {
    if (!Object.values(UserSpecialty).includes(specialty)) {
      throw new Error('Invalid specialty');
    }

    this.specialty = specialty;
    this.updatedAt = new Date();
  }

  // Getters
  getId(): string {
    return this.id;
  }

  getEmail(): string {
    return this.email.getValue();
  }

  getName(): string {
    return this.name;
  }

  getLastName(): string {
    return this.lastName;
  }

  getFullName(): string {
    return `${this.name} ${this.lastName}`;
  }

  getRole(): UserRole {
    return this.role;
  }

  getPhone(): string {
    return this.phone;
  }

  getSpecialty(): UserSpecialty {
    return this.specialty;
  }

  getAvatar(): string | null {
    return this.avatar;
  }

  getPasswordHash(): string {
    return this.passwordHash;
  }

  getIsActive(): boolean {
    return this.isActive;
  }

  getCreatedAt(): Date {
    return this.createdAt;
  }

  getUpdatedAt(): Date {
    return this.updatedAt;
  }

  // toPersistence: Means how the data will be stored in the database
  toPersistence(): Omit<UserPropsDomain, 'id'> {
    return {
      email: this.email,
      name: this.name,
      lastName: this.lastName,
      role: this.role,
      phone: this.phone,
      specialty: this.specialty,
      avatar: this.avatar,
      passwordHash: this.passwordHash,
      isActive: this.isActive,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }
}
