// Core map
export const QID_TO_PATH = {
  // Info básica
  1: 'informacionBasica.fecha',
  2: 'informacionBasica.nombreCompleto',
  3: 'informacionBasica.fechaNacimiento',
  4: 'informacionBasica.lugarNacimiento',
  5: 'informacionBasica.edad',
  6: 'informacionBasica.genero',
  7: 'informacionBasica.alturaCm',
  8: 'informacionBasica.pesoActualKg',
  9: 'informacionBasica.tallaCm',
  10: 'informacionBasica.ocupacion',
  11: 'informacionBasica.estadoCivil',
  12: 'informacionBasica.rfc',
  13: 'informacionBasica.correo',
  14: 'informacionBasica.domicilio',
  15: 'informacionBasica.telefonoCelular',
  16: 'informacionBasica.telefonoFijo',
  17: 'informacionBasica.contactoEmergencia',
  18: 'informacionBasica.telefonoEmergencia',

  // Info general
  19: 'informacionGeneral.motivoConsulta',
  20: 'informacionGeneral.alergiasConocidas',
  21: 'informacionGeneral.medicamentosActuales',
  22: 'informacionGeneral.buenEstadoSalud',
  23: 'informacionGeneral.bajoTratamiento',
  24: 'informacionGeneral.tomandoMedicamentos',
  25: 'informacionGeneral.alergicoMedicamentos',
  26: 'informacionGeneral.operadoHospitalizado',
  27: 'informacionGeneral.hemorragias',
  28: 'informacionGeneral.problemasCicatrizacion',
  29: 'informacionGeneral.otrasEnfermedades',
  30: 'informacionGeneral.enfermedades.diabetes',
  31: 'informacionGeneral.enfermedades.hipertension',
  32: 'informacionGeneral.enfermedades.hepatitis',
  33: 'informacionGeneral.enfermedades.vih',
  34: 'informacionGeneral.enfermedades.cancer',
  35: 'informacionGeneral.enfermedades.asma',
  36: 'informacionGeneral.enfermedades.epilepsia',
  37: 'informacionGeneral.enfermedades.gastritis',
  38: 'informacionGeneral.enfermedades.ansiedadDepresion',
  39: 'informacionGeneral.enfermedades.otras',
  40: 'informacionGeneral.consumoAlcohol',
  41: 'informacionGeneral.consumoTabaco',
  42: 'informacionGeneral.consumoDrogas',
  43: 'informacionGeneral.embarazo',
  44: 'informacionGeneral.lactancia',
  45: 'informacionGeneral.anticonceptivos',
  46: 'informacionGeneral.medicamentosPotencia',
  47: 'informacionGeneral.hijos',

  // Control de peso
  48: 'informacionClinica.controlPeso.pesoObjetivo',
  49: 'informacionClinica.controlPeso.actividadFisica',
  50: 'informacionClinica.controlPeso.horasSueno',
  51: 'informacionClinica.controlPeso.consumoAgua',
  52: 'informacionClinica.controlPeso.enfermedadesCronicas',
  53: 'informacionClinica.controlPeso.medicamentosActuales',
  54: 'informacionClinica.controlPeso.alergiasAlimentarias',
  55: 'informacionClinica.controlPeso.tipoAlimentacion',
  56: 'informacionClinica.controlPeso.cirugiasPrevias',
  57: 'informacionClinica.controlPeso.motivoConsultaPeso',

  // Odontología
  58: 'informacionClinica.odontologia.motivoConsultaOdonto',
  59: 'informacionClinica.odontologia.primeraVisita',
  60: 'informacionClinica.odontologia.visitaAnteriorAgradable',
  61: 'informacionClinica.odontologia.fluor',
  62: 'informacionClinica.odontologia.extraccionDientes',
  63: 'informacionClinica.odontologia.sangradoPostExtraccion',
  64: 'informacionClinica.odontologia.tratamientosPrevios',
  65: 'informacionClinica.odontologia.perdidaDientes',
  66: 'informacionClinica.odontologia.sangradoEncias',
  67: 'informacionClinica.odontologia.cepilladoDiario',
  68: 'informacionClinica.odontologia.enjuagueBucal',
  69: 'informacionClinica.odontologia.hiloDental',
  70: 'informacionClinica.odontologia.usaCepillo',
  71: 'informacionClinica.odontologia.dolorDental',
  72: 'informacionClinica.odontologia.tipoDolor',

  // Estética
  73: 'informacionClinica.estetica.motivoTratamiento',
  74: 'informacionClinica.estetica.cirugiasPrevias',
  75: 'informacionClinica.estetica.reaccionesAnestesia',
  76: 'informacionClinica.estetica.enfermedadesInterfieren',
  77: 'informacionClinica.estetica.condicionPiel',
  78: 'informacionClinica.estetica.zonaInteres',
  79: 'informacionClinica.estetica.tratamientosPrevios',
  80: 'informacionClinica.estetica.expectativas',
  81: 'informacionClinica.estetica.alergiasQuimicos',

  // Heredofamiliares
  82: 'antecedentes.heredofamiliares.diabetes',
  83: 'antecedentes.heredofamiliares.epilepsia',
  84: 'antecedentes.heredofamiliares.hepatitis',
  85: 'antecedentes.heredofamiliares.hipertension',
  86: 'antecedentes.heredofamiliares.malformaciones',
  87: 'antecedentes.heredofamiliares.artritis',

  // Personales patológicos
  88: 'antecedentes.personalesPatologicos.cardiopatias',
  89: 'antecedentes.personalesPatologicos.enfermedadesMentales',
  90: 'antecedentes.personalesPatologicos.neoplasias',
  91: 'antecedentes.personalesPatologicos.enfermedadesRenales',
  92: 'antecedentes.personalesPatologicos.varicela',
  93: 'antecedentes.personalesPatologicos.sarampion',
  94: 'antecedentes.personalesPatologicos.neuralgia',
  95: 'antecedentes.personalesPatologicos.viasBiliares',
  96: 'antecedentes.personalesPatologicos.asma',
  97: 'antecedentes.personalesPatologicos.enfermedadesRespiratorias',
  98: 'antecedentes.personalesPatologicos.hepatitis',
  99: 'antecedentes.personalesPatologicos.digestivo',
  100: 'antecedentes.personalesPatologicos.hipotiroidismo',
  101: 'antecedentes.personalesPatologicos.migraña',
  102: 'antecedentes.personalesPatologicos.epilepsia',
  103: 'antecedentes.personalesPatologicos.ansiedadDepresion',
  104: 'antecedentes.personalesPatologicos.hipertension',
  105: 'antecedentes.personalesPatologicos.diabetes',
  106: 'antecedentes.personalesPatologicos.cancer',
  107: 'antecedentes.personalesPatologicos.vih',
  108: 'antecedentes.personalesPatologicos.ets',
  109: 'antecedentes.personalesPatologicos.piel',
  110: 'antecedentes.personalesPatologicos.fracturas',
  111: 'antecedentes.personalesPatologicos.hospitalizaciones',
  112: 'antecedentes.personalesPatologicos.cirugias',
  113: 'antecedentes.personalesPatologicos.alteracionesHormonales',
  114: 'antecedentes.personalesPatologicos.hijos',
  115: 'antecedentes.personalesPatologicos.anticonceptivos',
  116: 'antecedentes.personalesPatologicos.embarazo',
  117: 'antecedentes.personalesPatologicos.lactancia',

  // No patológicos
  118: 'antecedentes.noPatologicos.tipoAlimentacion',
  119: 'antecedentes.noPatologicos.comidasDia',
  120: 'antecedentes.noPatologicos.intolerancias',
  121: 'antecedentes.noPatologicos.alimentosNoConsume',
  122: 'antecedentes.noPatologicos.lavadoManos',
  123: 'antecedentes.noPatologicos.usoCepillo',
  124: 'antecedentes.noPatologicos.usoEnjuague',
  125: 'antecedentes.noPatologicos.usoHilo',

  // Inmunizaciones
  126: 'antecedentes.inmunizaciones.poliomielitis',
  127: 'antecedentes.inmunizaciones.tuberculosis',
  128: 'antecedentes.inmunizaciones.dtp',
  129: 'antecedentes.inmunizaciones.tripleViral',
  130: 'antecedentes.inmunizaciones.sarampion',
  131: 'antecedentes.inmunizaciones.hepatitisB',
  132: 'antecedentes.inmunizaciones.otras',

  // Hábitos
  133: 'antecedentes.habitos.alcohol',
  134: 'antecedentes.habitos.tabaco',
  135: 'antecedentes.habitos.drogas',
  136: 'antecedentes.habitos.deportes',

  // Exploración física
  137: 'exploracionFisica.cabeza',
  138: 'exploracionFisica.cuello',
  139: 'exploracionFisica.torax',
  140: 'exploracionFisica.abdomen',
  141: 'exploracionFisica.extremidades',

  // Signos vitales
  142: 'signosVitales.tensionArterial',
  143: 'signosVitales.frecuenciaCardiaca',
  144: 'signosVitales.frecuenciaRespiratoria',
  145: 'signosVitales.temperatura',
  146: 'signosVitales.saturacionOxigeno',
  147: 'signosVitales.imc',
  148: 'signosVitales.peso',
  149: 'signosVitales.talla',

  // Campos del médico: datos clínicos
  150: 'camposMedico.datosClinicos.fechaRegistro',
  151: 'camposMedico.datosClinicos.medicoResponsable',
  152: 'camposMedico.datosClinicos.diagnosticoPreliminar',
  153: 'camposMedico.datosClinicos.tratamientoSugerido',
  154: 'camposMedico.datosClinicos.notas',

  // Campos del médico: odontología
  155: 'camposMedico.odontologia.cavidadBucal',
  156: 'camposMedico.odontologia.cuelloEstructuras',
  157: 'camposMedico.odontologia.diagnosticoDental',
  158: 'camposMedico.odontologia.planTratamientoDental',
  159: 'camposMedico.odontologia.materialesUsados',
  160: 'camposMedico.odontologia.recomendacionesPaciente',

  // Campos del médico: estética
  161: 'camposMedico.estetica.diagnosticoFacial',
  162: 'camposMedico.estetica.condicionPiel',
  163: 'camposMedico.estetica.zonasTratadas',
  164: 'camposMedico.estetica.productoTecnica',
  165: 'camposMedico.estetica.fechaTratamiento',
  166: 'camposMedico.estetica.evolucion',
  167: 'camposMedico.estetica.complicaciones',
  168: 'camposMedico.estetica.recomendacionesPost',

  // Seguimiento
  169: 'camposMedico.seguimiento.diagnosticoDefinitivo',
  170: 'camposMedico.seguimiento.tratamientoPrescrito',
  171: 'camposMedico.seguimiento.medicamentosIndicados',
  172: 'camposMedico.seguimiento.observacionesEvolucion',
  173: 'camposMedico.seguimiento.recomendacionesFinales',
  174: 'camposMedico.seguimiento.fechaRevisionSiguiente',
  175: 'camposMedico.seguimiento.firmaMedico',

  // Complementos
  176: 'complementos.pasatiempos',
  177: 'complementos.comoSeEntero',
  178: 'complementos.adultoResponsable',
  179: 'complementos.recomendadoPor',
  180: 'complementos.observacionesPersonales',
  181: 'complementos.comentarioLibre',
};
