import { GoalStatusEnum, UserSpecialty } from '@/domain/enums/';

export interface GoalPropsDomain {
  id: string;
  patientId: string;
  consultationId: string;
  specialty: UserSpecialty;
  initialValue: number;
  targetValue: number;
  finalValue?: number;
  status: GoalStatusEnum;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export class Goal {
  private id: string;
  private patientId: string;
  private consultationId: string;
  private specialty: UserSpecialty;
  private initialValue: number;
  private targetValue: number;
  private finalValue?: number;
  private status: GoalStatusEnum;
  private notes?: string;
  private readonly createdAt: Date;
  private updatedAt: Date;

  private constructor(props: GoalPropsDomain) {
    this.id = props.id;
    this.patientId = props.patientId;
    this.consultationId = props.consultationId;
    this.specialty = props.specialty;
    this.initialValue = props.initialValue;
    this.targetValue = props.targetValue;
    this.status = props.status;
    this.notes = props.notes;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;
  }

  static create(props: {
    patientId: string;
    consultationId: string;
    specialty: UserSpecialty;
    initialValue: number;
    targetValue: number;
    notes?: string;
  }): Goal {
    if (!props.patientId) throw new Error('Patient ID is required');
    if (!props.consultationId) throw new Error('Consultation ID is required');

    const now = new Date();

    return new Goal({
      id: '', // ID will be generated by the database
      patientId: props.patientId,
      consultationId: props.consultationId,
      specialty: props.specialty,
      initialValue: props.initialValue,
      targetValue: props.targetValue,
      status: GoalStatusEnum.ACTIVE,
      notes: props.notes,
      createdAt: now,
      updatedAt: now,
    });
  }

  static fromPersistence(props: GoalPropsDomain): Goal {
    if (!props.id) throw new Error('Invalid goal id');
    return new Goal(props);
  }

  //! Behavior
  complete(finalValue: number): void {
    const isLoss = this.targetValue < this.initialValue;

    if (isLoss && finalValue > this.targetValue) {
      throw new Error(
        `Goal cannot be completed: final weight (${finalValue}kg) is still above target (${this.targetValue}kg)`
      );
    }

    if (!isLoss && finalValue < this.targetValue) {
      throw new Error(
        `Goal cannot be completed: final value (${finalValue}) is still below target (${this.targetValue})`
      );
    }

    this.status = GoalStatusEnum.COMPLETED;
    this.finalValue = finalValue;
    this.updatedAt = new Date();
  }

  fail(finalValue: number): void {
    const isLoss = this.targetValue < this.initialValue;

    if (isLoss && finalValue <= this.targetValue) {
      throw new Error(
        `Goal cannot be failed: final weight (${finalValue}kg) is already at or below target (${this.targetValue}kg)`
      );
    }

    if (!isLoss && finalValue >= this.targetValue) {
      throw new Error(
        `Goal cannot be failed: final value (${finalValue}) is already at or above target (${this.targetValue})`
      );
    }

    this.status = GoalStatusEnum.FAILED;
    this.finalValue = finalValue;
    this.updatedAt = new Date();
  }

  cancel(): void {
    this.status = GoalStatusEnum.CANCELLED;
    this.updatedAt = new Date();
  }

  // Getters
  getId(): string {
    return this.id;
  }
  getPatientId(): string {
    return this.patientId;
  }
  getConsultationId(): string {
    return this.consultationId;
  }
  getSpecialty(): UserSpecialty {
    return this.specialty;
  }
  getInitialValue(): number {
    return this.initialValue;
  }
  getTargetValue(): number {
    return this.targetValue;
  }
  getFinalValue(): number | undefined {
    return this.finalValue;
  }
  getStatus(): GoalStatusEnum {
    return this.status;
  }
  getNotes(): string | undefined {
    return this.notes;
  }
  getCreatedAt(): Date {
    return this.createdAt;
  }
  getUpdatedAt(): Date {
    return this.updatedAt;
  }

  toPersistence(): Omit<GoalPropsDomain, 'id'> {
    return {
      patientId: this.patientId,
      consultationId: this.consultationId,
      specialty: this.specialty,
      initialValue: this.initialValue,
      targetValue: this.targetValue,
      finalValue: this.finalValue,
      status: this.status,
      notes: this.notes,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }
}
